[package]
name = "belt-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
assembly-compiler = { path = "../assembly-compiler" }
itertools = "0.14.0"
parse_int = "0.9.0"
    
[dev-dependencies]
